### ISSUE TITLE
Update the hotspot script

### ISSUE THREAD

**Issue by mmattamala** [Duckietown-Chile/Software#1]
Update the script to:

1. Change default ip address (10.42.0.x -> 11.0.0.x) ore something similar
2. Include the chance to change the channel
3. Use a better way to power on/off the hotspot that doesn't depend on the environment variables. For  example, using a flag in the script:
`source hotspot.sh on`

**Comment by mcamp** [comment]
Number 3 is done in:
https://github.com/Duckietown-Chile/Software/commit/66475254aba93489cbac3c7b10b3fa623f7fb9cf
However, it still need to be tested in a real duckie

**Comment by mmattamala** [comment]
The hotspot works
